### ISSUE TITLE
analysis rendering performance

### ISSUE THREAD

**Issue by timruffles** [sidekickcode/tracker#171]
## TODOs
- [ ] initial load - extremely expensive render for initial file lists (easily 5seconds on large repo)
- [x] progress - expensive deep compares used to keep total issues list unique, gets slower with each new issue
- [ ] ng animate - very costly animation calls, likely to ng-repeat
### Initial render

e.g 1.5s render on sk deployed repo full analysis. Breaks down into 2x ng-repeat renders (I believe that's analysed & non-analysed files), and 1x animation call.

<img width="873" alt="screen shot 2016-01-06 at 11 35 31" src="https://cloud.githubusercontent.com/assets/249800/12141709/c7886658-b469-11e5-911e-9cf1d1cb4d6f.png">

More detail:

<img width="797" alt="5second frame" src="https://cloud.githubusercontent.com/assets/249800/13028401/eb4dd1c6-d265-11e5-92d2-31cfb8b4f284.png">
### Progress update cost

<img width="1170" alt="update-meta-slow" src="https://cloud.githubusercontent.com/assets/249800/13028406/16d28f12-d266-11e5-99af-d44fe27b82d1.png">
### Animation

<img width="704" alt="screen shot 2016-02-13 at 20 47 48" src="https://cloud.githubusercontent.com/assets/249800/13029978/2435bd3c-d293-11e5-8293-a2c32a33f6d2.png">

**Comment by timruffles** [comment]
<img width="797" alt="5second frame" src="https://cloud.githubusercontent.com/assets/249800/13028401/eb4dd1c6-d265-11e5-92d2-31cfb8b4f284.png">

**Comment by timruffles** [comment]
<img width="1170" alt="update-meta-slow" src="https://cloud.githubusercontent.com/assets/249800/13028406/16d28f12-d266-11e5-99af-d44fe27b82d1.png">

**Comment by rishson** [comment]
Yep - analysisMeta.processUpdate should be easy pickings. It reconstructs all the meta each update rather than appending.

**Comment by timruffles** [comment]
processUpdate is no longer an issue:

<img width="821" alt="screen shot 2016-02-13 at 20 41 54" src="https://cloud.githubusercontent.com/assets/249800/13029970/bea92bac-d292-11e5-9046-81c13bebae43.png">

**Comment by timruffles** [comment]
With a limit 10 on all repeats, we get very low jank (red marks) on the UI. Pagination would achieve this

<img width="1280" alt="screen shot 2016-02-13 at 21 05 59" src="https://cloud.githubusercontent.com/assets/249800/13030096/2e36a5fe-d297-11e5-8618-cc16ce88053b.png">
